schema: "classroom50/repo-config/v1"
classroom: "ut-austin-cs378-cloud-computing"
assignment: "cs378-assignment-2"
owner:
  username: "SanaShan1229"
  id: 175969092
  accepted_at: "2026-09-14T19:21:16Z"
source:
  owner: "kiat"
  owner_id: 1133111
  repo: "cloud-template-a2"
  branch: "main"
